## Kaggle Dataset Link
https://www.kaggle.com/datasets/waqi786/student-performance-dataset

**Excel Calculations File** <br>
https://docs.google.com/spreadsheets/d/1IN1wGPNtiE0RqQlKngGKaCg7KIpYJMVRRTvzRD9R9HM/edit?usp=sharing

In [ ]:
#import the required libraries
import pandas as pd ##
import numpy as np ##
import matplotlib.pyplot as plt
import seaborn as sns

#import sklearn functions
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler ##

In [ ]:
#import the raw data
df = pd.read_csv('/content/student_performance_data.csv')

#check the shape
df.shape

(500, 9)

In [ ]:
#splitting the data even when we won't perform model predictions to avoid data leakage
X_train, X_test, y_train, y_test = train_test_split(df.drop('GPA', axis=1), df['GPA'], test_size=0.2, random_state=42)

# Normalization

**Official Documentation** <br>
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [ ]:
#define the variables I wanna scale
cols_to_scale = ["StudyHoursPerWeek", "AttendanceRate", "GPA"]

scaler_norm = MinMaxScaler()
scaled_data = scaler_norm.fit_transform(df[cols_to_scale])
scaled_df = pd.DataFrame(scaled_data, columns=cols_to_scale)

#display the first few rows
scaled_df.head(3)

   StudyHoursPerWeek  AttendanceRate       GPA
0           0.947368        0.815452  0.738693
1           0.947368        0.498199  0.160804
2           0.236842        0.067054  0.190955

## Validate Our Calculations (for Normalization)

In [ ]:
# for normalization
print(f'StudyHoursPerWeek has Min: {scaled_df["StudyHoursPerWeek"].min()}, Max: {scaled_df["StudyHoursPerWeek"].max()}')
print(f'AttendanceRate has Min: {scaled_df["AttendanceRate"].min()}, Max: {scaled_df["AttendanceRate"].max()}')
print(f'GPA has Min: {scaled_df["GPA"].min()}, Max: {scaled_df["GPA"].max()}')

StudyHoursPerWeek has Min: 0.0, Max: 0.9999999999999999
AttendanceRate has Min: 0.0, Max: 1.0
GPA has Min: 0.0, Max: 1.0

# Standardization

**Official Documentation** <br>
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [ ]:
#define the variables I wanna scale
cols_to_scale = ["StudyHoursPerWeek", "AttendanceRate", "GPA"]

scaler_stand = StandardScaler()
scaled_data = scaler_stand.fit_transform(df[cols_to_scale])
scaled_df = pd.DataFrame(scaled_data, columns=cols_to_scale)

#display the first few rows
scaled_df.head(3)

   StudyHoursPerWeek  AttendanceRate       GPA
0           1.494258        1.083035  0.861086
1           1.494258       -0.006211 -1.181338
2          -0.861790       -1.486487 -1.074777

## Validate Our Calculations (for Standardization)

Mean should be 0
and variance should be 1

However, as you can see in the next calculations we see the mean has a negative value and a lot of digits next to it. It happens due to two main reasons (Floating-point precision limits) and (Degrees of Freedom (ddof))

1. **Floating-point precision limits**: Computers represent real numbers using binary floating points. Calculations like subtracting the mean can leave extremely tiny residual decimals (e.g., $10^{-16}$$10^{-16}$). This is practically equivalent to 0.

2. **Degrees of Freedom (ddof)**: By default, scikit-learn's StandardScaler standardizes your data using Population Variance (divided by $N$$N$). However, Pandas' .var() function calculates Sample Variance by default (divided by $N - 1$$N - 1$, which is ddof=1).

*To ensure we get the same results as we did in the excel file, kindly check the 2nd code cell*

In [ ]:
# for standardization
print(f"'StudyHoursPerWeek' has Exact Mean: {scaled_df["StudyHoursPerWeek"].mean()}, Exact Variance: {scaled_df["StudyHoursPerWeek"].var()}")
print(f"'AttendanceRate' has Exact Mean: {scaled_df["AttendanceRate"].mean()}, Exact Variance: {scaled_df["AttendanceRate"].var()}")
print(f"'GPA' has Exact Mean: {scaled_df["GPA"].mean()}, Exact Variance: {scaled_df["GPA"].var()}")

'StudyHoursPerWeek' has Exact Mean: -1.1013412404281553e-16, Exact Variance: 1.0020040080160295
'AttendanceRate' has Exact Mean: -1.1235457009206584e-16, Exact Variance: 1.0020040080160328
'GPA' has Exact Mean: -8.562039965909207e-16, Exact Variance: 1.0020040080160313

In [ ]:
# enhancing the numbers of standardization
print(f"'StudyHoursPerWeek' has Exact Mean: {abs(scaled_df["StudyHoursPerWeek"].mean().round())}, Exact Variance: {round(scaled_df["StudyHoursPerWeek"].var())}")
print(f"'AttendanceRate' has Exact Mean: {abs(scaled_df["AttendanceRate"].mean().round())}, Exact Variance: {round(scaled_df["AttendanceRate"].var())}")
print(f"'GPA' has Exact Mean: {abs(scaled_df["GPA"].mean().round())}, Exact Variance: {round(scaled_df["GPA"].var())}")

'StudyHoursPerWeek' has Exact Mean: 0.0, Exact Variance: 1
'AttendanceRate' has Exact Mean: 0.0, Exact Variance: 1
'GPA' has Exact Mean: 0.0, Exact Variance: 1

# Numpy Library

Let's apply the statistical calculations using purly numpy

In [ ]:
# each row represents the x value
df.GPA.head(2)

0    3.47
1    2.32
Name: GPA, dtype: float64

In [ ]:
# Define the equations
# Normalization = (X - X_min) / (X_max - X_min)
# Standardization = (X - mean) / std

min_gpa = df.GPA.min()
max_gpa = df.GPA.max()

print(min_gpa, max_gpa)

2.0 3.99

In [ ]:
# Create a new column with the new scaled values
# for normalization
df["GPA_scaled"] = (df.GPA - min_gpa) / (max_gpa - min_gpa)
df["GPA_scaled"].head(3)

0    0.738693
1    0.160804
2    0.190955
Name: GPA_scaled, dtype: float64

In [14]:
# validating that the new scaled values (normalization) are correct!
print(f"'GPA_scaled' has Exact Mean: {df["GPA_scaled"].min()}, Exact Variance: {df["GPA_scaled"].max()}")

'GPA_scaled' has Exact Mean: 0.0, Exact Variance: 1.0

In [15]:
# for standardization
gpa_mean = df.GPA.mean()
gpa_std = df.GPA.std()

df["GPA_standardized"] = (df.GPA - gpa_mean) / gpa_std
df["GPA_standardized"].head(3)

0    0.860224
1   -1.180156
2   -1.073701
Name: GPA_standardized, dtype: float64

In [16]:
# validating that the new scaled values (standardization) are correct!
print(f"'GPA_standardized' has Exact Mean: {df["GPA_standardized"].mean()}, Exact Variance: {df["GPA_standardized"].var()}")

'GPA_standardized' has Exact Mean: -8.668621376273222e-16, Exact Variance: 1.0000000000000002