## Kaggle Dataset Link
https://www.kaggle.com/datasets/waqi786/student-performance-dataset

**Excel Calculations File** <br>
https://docs.google.com/spreadsheets/d/1IN1wGPNtiE0RqQlKngGKaCg7KIpYJMVRRTvzRD9R9HM/edit?usp=sharing

In [1]:
#import the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#import sklearn functions
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
#import the raw data
df = pd.read_csv('/content/student_performance_data.csv')

#check the shape
df.shape

(500, 9)

In [3]:
#splitting the data even when we won't perform model predictions to avoid data leakage
X_train, X_test, y_train, y_test = train_test_split(df.drop('GPA', axis=1), df['GPA'], test_size=0.2, random_state=42)

# Normalization

**Official Documentation** <br>
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [13]:
#define the variables I wanna scale
cols_to_scale = ["StudyHoursPerWeek", "AttendanceRate", "GPA"]

scaler_norm = MinMaxScaler()
scaled_data = scaler_norm.fit_transform(df[cols_to_scale])
scaled_df = pd.DataFrame(scaled_data, columns=cols_to_scale)

scaled_df.head()

   StudyHoursPerWeek  AttendanceRate       GPA
0           0.947368        0.815452  0.738693
1           0.947368        0.498199  0.160804
2           0.236842        0.067054  0.190955
3           0.236842        0.405324  0.733668
4           0.473684        0.497598  0.155779

## Validate Our Calculations (for Normalization)

In [14]:
# for normalization
print(f'Min Value: {scaled_df["StudyHoursPerWeek"].min()}')
print(f'Max Value: {scaled_df["StudyHoursPerWeek"].max()}')

print(f'Min Value: {scaled_df["AttendanceRate"].min()}')
print(f'Max Value: {scaled_df["AttendanceRate"].max()}')

print(f'Min Value: {scaled_df["GPA"].min()}')
print(f'Max Value: {scaled_df["GPA"].max()}')

Min Value: 0.0
Max Value: 0.9999999999999999
Min Value: 0.0
Max Value: 1.0
Min Value: 0.0
Max Value: 1.0

# Standardization

**Official Documentation** <br>
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [16]:
#define the variables I wanna scale
cols_to_scale = ["StudyHoursPerWeek", "AttendanceRate", "GPA"]

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df[cols_to_scale])
scaled_df = pd.DataFrame(scaled_data, columns=cols_to_scale)

scaled_df.head()

   StudyHoursPerWeek  AttendanceRate       GPA
0           1.494258        1.083035  0.861086
1           1.494258       -0.006211 -1.181338
2          -0.861790       -1.486487 -1.074777
3          -0.861790       -0.325082  0.843326
4          -0.076441       -0.008273 -1.199098

## Validate Our Calculations (for Standardization)

Mean should be 0
and variance should be 1

However, as you can see in the next calculations we see the mean has a negative value and a lot of digits next to it. It happens due to two main reasons (Floating-point precision limits) and (Degrees of Freedom (ddof))

1. **Floating-point precision limits**: Computers represent real numbers using binary floating points. Calculations like subtracting the mean can leave extremely tiny residual decimals (e.g., $10^{-16}$$10^{-16}$). This is practically equivalent to 0.

2. **Degrees of Freedom (ddof)**: By default, scikit-learn's StandardScaler standardizes your data using Population Variance (divided by $N$$N$). However, Pandas' .var() function calculates Sample Variance by default (divided by $N - 1$$N - 1$, which is ddof=1).

*To ensure we get the same results as we did in the excel file, kindly check the 2nd code cell*

In [39]:
# for standardization
print(f"'StudyHoursPerWeek' has Exact Mean: {scaled_df["StudyHoursPerWeek"].mean()}, Exact Variance: {scaled_df["StudyHoursPerWeek"].var()}")
print(f"'AttendanceRate' has Exact Mean: {scaled_df["AttendanceRate"].mean()}, Exact Variance: {scaled_df["AttendanceRate"].var()}")
print(f"'GPA' has Exact Mean: {scaled_df["GPA"].mean()}, Exact Variance: {scaled_df["GPA"].var()}")

'StudyHoursPerWeek' has Exact Mean: -1.1013412404281553e-16, Exact Variance: 1.0020040080160295
'AttendanceRate' has Exact Mean: -1.1235457009206584e-16, Exact Variance: 1.0020040080160328
'GPA' has Exact Mean: -8.562039965909207e-16, Exact Variance: 1.0020040080160313

In [35]:
# enhancing the numbers of standardization
print(f"'StudyHoursPerWeek' has Exact Mean: {abs(scaled_df["StudyHoursPerWeek"].mean().round())}, Exact Variance: {round(scaled_df["StudyHoursPerWeek"].var())}")
print(f"'AttendanceRate' has Exact Mean: {abs(scaled_df["AttendanceRate"].mean().round())}, Exact Variance: {round(scaled_df["AttendanceRate"].var())}")
print(f"'GPA' has Exact Mean: {abs(scaled_df["GPA"].mean().round())}, Exact Variance: {round(scaled_df["GPA"].var())}")

'StudyHoursPerWeek' has Exact Mean: 0.0, Exact Variance: 1
'AttendanceRate' has Exact Mean: 0.0, Exact Variance: 1
'GPA' has Exact Mean: 0.0, Exact Variance: 1